### ISSUE TITLE
Ensure that versions are based on the `gitspace-plugin.toml` and `gitspace-template.toml` files

### ISSUE THREAD

**Issue by alechp** [ssotops/gitspace-catalog#9]
Relevant to GH & Dagger workflow

Context:
```toml
[catalog]
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "0.1.1"
last_updated = { date = "2024-09-09T21:25:40-07:00", commit_hash = "placeholder_hash" }

[plugins]
[plugins.templates]
version = "0.1.0"
description = "A Gitspace plugin"
path = "/Users/alechp/.ssot/gitspace/.repositories/github.com/ssotops/gitspace-catalog/plugins/templates"

[templates]
[templates.gitspace-plugin-starter]
version = "0.1.0"
description = "A Gitspace plugin"
path = "/Users/alechp/.ssot/gitspace/.repositories/github.com/ssotops/gitspace-catalog/templates/gitspace-plugin-starter"

[templates.gitspace-catalog-starter]
path = "/Users/alechp/.ssot/gitspace/.repositories/github.com/ssotops/gitspace-catalog/templates/gitspace-catalog-starter"
```
